### ISSUE TITLE
[Feat/Refactor] Code Review Reflection / BindingAdapter

### ISSUE THREAD

**Issue by IslandofDream** [Team-AngDroid/Refrigerator_Management#39]
## 🔈 Issue
#38
#26 
에서 반영하지 못한 혹은 논의가 덜 끝나 반영되지 않은 코드들을 수정하고자 합니다 

![식재료 리스트](https://user-images.githubusercontent.com/70648111/198839497-aa1a2d7e-169f-426f-84a4-2a1be4174b2a.png) ![Group 1212](https://user-images.githubusercontent.com/70648111/198839756-8987c32a-f40c-44f3-aaa4-1a85e153befd.png)

바인딩 어댑터 작업 또한 같이 진행하고자 합니다. 

## 📑 To-do
- [x] CodeReivew Reflection
- [x] Adapter
- [x] View
- [x] Refactor
- [x] Count BindingAdapter
- [x] Connect link by Implict intent

**Comment by KkamSonLee** [comment]
PR 태그 아주 좋습니다!!
